version: '3.8'

services:
  frontend:
    build:
      context: .  # Ruta donde está el Dockerfile del frontend
      dockerfile: Dockerfile  # Usar el Dockerfile en la raíz
    ports:
      - "80:80"  # Mapea el puerto 80 del contenedor al puerto 80 del host
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./bufi-file-managment  # Ruta donde está el Dockerfile del backend
      dockerfile: Dockerfile  # Usar el Dockerfile en bufi-file-managment
    ports:
      - "3000:3000"  # Mapea el puerto 3000 del contenedor al puerto 3000 del host
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
