/**
 * Turtle Nest Monitoring Persistence DB API
 * This projects establish the connection with the database, we don't have any logicimplemented in this project, since we only use this to save, consult and update information
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { NestsReq } from './nestsReq';

/**
 * Record object that needs to be added
 */
export interface RecordsReq { 
    id?: number;
    nest?: NestsReq;
    samplingDateTime?: Date;
    temperature?: number;
    humidityPercentage?: number;
    energy?: number;
    x?: number;
    y?: number;
    z?: number;
    isTesting?: boolean;
    recordNumber?: number;
    day?: number;
}